/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    patientId?: string;
                    doctorId?: string;
                    status?: "draft" | "in_progress" | "completed" | "signed_off";
                    dateFrom?: string;
                    dateTo?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                patientId: string;
                                appointmentId?: string | null;
                                /** Format: uuid */
                                doctorId: string;
                                specialtyId?: number | null;
                                encounterDate: string;
                                /** @enum {string} */
                                encounterType: "outpatient" | "inpatient" | "emergency" | "telehealth" | "follow_up";
                                /** @enum {string} */
                                status: "draft" | "in_progress" | "completed" | "signed_off";
                                chiefComplaint?: string | null;
                                historyOfPresentIllness?: string | null;
                                diagnosisPrimary?: string | null;
                                diagnosisSecondary: unknown[];
                                clinicalNotes?: string | null;
                                vitalSigns: {
                                    [key: string]: unknown;
                                };
                                prescriptions: unknown[];
                                labOrders: unknown[];
                                followUpDate?: string | null;
                                followUpNotes?: string | null;
                                signedOffBy?: string | null;
                                signedOffAt?: string | null;
                                version: number;
                                createdBy?: string | null;
                                createdAt: string;
                                updatedAt: string;
                                branchId: number;
                            }[];
                            total: number;
                            page: number;
                            limit: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/encounters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                patientId: string;
                                appointmentId?: string | null;
                                /** Format: uuid */
                                doctorId: string;
                                specialtyId?: number | null;
                                encounterDate: string;
                                /** @enum {string} */
                                encounterType: "outpatient" | "inpatient" | "emergency" | "telehealth" | "follow_up";
                                /** @enum {string} */
                                status: "draft" | "in_progress" | "completed" | "signed_off";
                                chiefComplaint?: string | null;
                                historyOfPresentIllness?: string | null;
                                diagnosisPrimary?: string | null;
                                diagnosisSecondary: unknown[];
                                clinicalNotes?: string | null;
                                vitalSigns: {
                                    [key: string]: unknown;
                                };
                                prescriptions: unknown[];
                                labOrders: unknown[];
                                followUpDate?: string | null;
                                followUpNotes?: string | null;
                                signedOffBy?: string | null;
                                signedOffAt?: string | null;
                                version: number;
                                createdBy?: string | null;
                                createdAt: string;
                                updatedAt: string;
                                branchId: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/encounters/{id}/sign-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patientId}/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: "draft" | "in_progress" | "completed" | "signed_off";
                    dateFrom?: string;
                    dateTo?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    patientId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                patientId: string;
                                appointmentId?: string | null;
                                /** Format: uuid */
                                doctorId: string;
                                specialtyId?: number | null;
                                encounterDate: string;
                                /** @enum {string} */
                                encounterType: "outpatient" | "inpatient" | "emergency" | "telehealth" | "follow_up";
                                /** @enum {string} */
                                status: "draft" | "in_progress" | "completed" | "signed_off";
                                chiefComplaint?: string | null;
                                historyOfPresentIllness?: string | null;
                                diagnosisPrimary?: string | null;
                                diagnosisSecondary: unknown[];
                                clinicalNotes?: string | null;
                                vitalSigns: {
                                    [key: string]: unknown;
                                };
                                prescriptions: unknown[];
                                labOrders: unknown[];
                                followUpDate?: string | null;
                                followUpNotes?: string | null;
                                signedOffBy?: string | null;
                                signedOffAt?: string | null;
                                version: number;
                                createdBy?: string | null;
                                createdAt: string;
                                updatedAt: string;
                                branchId: number;
                            }[];
                            total: number;
                            page: number;
                            limit: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prescriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    patientId?: string;
                    doctorId?: string;
                    encounterId?: string;
                    status?: "active" | "dispensed" | "cancelled";
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prescriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prescriptions/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/medications/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autocomplete search across EDA medicine & cosmetic registry */
        get: {
            parameters: {
                query: {
                    /** @description Trade name, generic name, or active ingredient (Arabic or English) */
                    q: string;
                    /** @description Filter by product type; omit for both */
                    type?: "medicine" | "cosmetic";
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            query?: string;
                            total?: number;
                            data?: {
                                /** Format: uuid */
                                id?: string;
                                tradeNameEn?: string;
                                tradeNameAr?: null | string;
                                /** @enum {string} */
                                type?: "medicine" | "cosmetic";
                                genericNameEn?: null | string;
                                strength?: null | string;
                                formCode?: null | string;
                                formNameEn?: null | string;
                                formNameAr?: null | string;
                                prescriptionRequired?: null | boolean;
                                controlledSubstance?: null | boolean;
                                rank?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
