/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    ids: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: {
                                /** Format: uuid */
                                patientId: string;
                                mobile: string;
                                mobileHistory: string[];
                                nationalId?: string | null;
                                nameEn: string;
                                nameAr?: string | null;
                                dateOfBirth?: string | null;
                                /** @enum {string|null} */
                                gender?: "M" | "F" | null;
                                /** @enum {string|null} */
                                bloodType?: "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-" | null;
                                address?: string | null;
                                email?: string | null;
                                emergencyContactMobile?: string | null;
                                emergencyContactName?: string | null;
                                /** @enum {string} */
                                preferredLanguage: "ar" | "en";
                                sourceFirstVisit?: string | null;
                                isFutureSource: boolean;
                                futureSourceType?: string | null;
                                futureSourceSetAt?: string | null;
                                futureSourceSetBy?: string | null;
                                deletedAt?: string | null;
                                version: number;
                                createdAt: string;
                                updatedAt: string;
                                createdBy?: string | null;
                                branchId: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    query?: string;
                    mobile?: string;
                    nationalId?: string;
                    isFutureSource?: boolean;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            data: {
                                /** Format: uuid */
                                patientId: string;
                                mobile: string;
                                mobileHistory: string[];
                                nationalId?: string | null;
                                nameEn: string;
                                nameAr?: string | null;
                                dateOfBirth?: string | null;
                                /** @enum {string|null} */
                                gender?: "M" | "F" | null;
                                /** @enum {string|null} */
                                bloodType?: "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-" | null;
                                address?: string | null;
                                email?: string | null;
                                emergencyContactMobile?: string | null;
                                emergencyContactName?: string | null;
                                /** @enum {string} */
                                preferredLanguage: "ar" | "en";
                                sourceFirstVisit?: string | null;
                                isFutureSource: boolean;
                                futureSourceType?: string | null;
                                futureSourceSetAt?: string | null;
                                futureSourceSetBy?: string | null;
                                deletedAt?: string | null;
                                version: number;
                                createdAt: string;
                                updatedAt: string;
                                createdBy?: string | null;
                                branchId: number;
                            }[];
                            total: number;
                            page: number;
                            limit: number;
                            totalPages: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
